services:
  db:
    image: postgres:alpine
    env_file: .env
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - psql_volume:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
        ]
      interval: 1s
      timeout: 5s
      retries: 10
