[project]
name = "pc-components-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.10.6",
    "pandas>=2.2.3",
]
